# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SensorMsg.proto',
  package='tutorial',
  syntax='proto3',
  serialized_options=_b('\252\002\tSensorMsg'),
  serialized_pb=_b('\n\x0fSensorMsg.proto\x12\x08tutorial\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n\nSensorData\x12\x14\n\x0c\x62\x61tteryLevel\x18\x01 \x01(\x01\x12\x0e\n\x06Motion\x18\x02 \x01(\x08\x12\x13\n\x0bUltraviolet\x18\x03 \x01(\x01\x12\x11\n\tLuminance\x18\x04 \x01(\x01\x12\x18\n\x10RelativeHumidity\x18\x05 \x01(\x01\x12\x13\n\x0bTemperature\x18\x06 \x01(\x01\x12\x30\n\x0clast_updated\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x0c\xaa\x02\tSensorMsgb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_SENSORDATA = _descriptor.Descriptor(
  name='SensorData',
  full_name='tutorial.SensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='batteryLevel', full_name='tutorial.SensorData.batteryLevel', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Motion', full_name='tutorial.SensorData.Motion', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Ultraviolet', full_name='tutorial.SensorData.Ultraviolet', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Luminance', full_name='tutorial.SensorData.Luminance', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RelativeHumidity', full_name='tutorial.SensorData.RelativeHumidity', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Temperature', full_name='tutorial.SensorData.Temperature', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_updated', full_name='tutorial.SensorData.last_updated', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=250,
)

_SENSORDATA.fields_by_name['last_updated'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['SensorData'] = _SENSORDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorData = _reflection.GeneratedProtocolMessageType('SensorData', (_message.Message,), {
  'DESCRIPTOR' : _SENSORDATA,
  '__module__' : 'SensorMsg_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.SensorData)
  })
_sym_db.RegisterMessage(SensorData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
